language: ruby
rvm:
- 2.2.4
deploy:
  provider: heroku
  api_key:
    secure: lKyIXG+8+UP7xwBRb8pqo6Ar61ayakckRSU8K3Ncm55DZHsqjC1+MH/0lijHek05+1qmy95r/rV592KKGYX3YZB0b+irM29Ho1MhcalvBEDmbryENOaGA0WeD3YxJFcUFEI5O5Kbx1Odne2bhmDIHa2aIvtN62JM4a70XNKZh5s85zkf8SwvVn6Q+COjO3hcoGqdGElzGoCm4DcC0YckJ5czJ0ppXn6qnvL840qHY4S5VKGzQqm2oqEvqxHRGWkx22f6E1wJCfjrDpJf9vNA3X9TJZbIMZtPRjDxF7iW7slcYiRWFWqGIWRjBUZxJERkc+rU+zcN3ulDgk9HsYgrpEMfyjORT3jkEmXycL6nffQ2/GUJyAT3Jwd+LqdGyPcXLDQuKnhmHkw6D8nvvXUi0eKo6MkB6e2XmBWW3isQdMwdTQdX4uPkWqvxXcbMKMxxLfkLoPYLAXNtQO3FQPLr3Jj8VjI1R7qVuMbi9Uku/iH8ssEFEonMxzc4oPQsctVnGxvFiyFrmH8IZJ4I0h6qfbrxMTUGF0PcD6PflOEjob7cg9VxoCDkXSKcWl3Ofs20PDUmwku9qY/xlDohdCNEeGVsIpZbrksxsNDPFkYg/TnLDPc3JuhjYvCkt6fiPKjSCGJCbJYmh1VkPSwBtUMStnXtgJBhHiRgiWcGZ6UcthI=
  app: murmuring-headland-50346
  on:
    repo: MeyerEsther/projet
